name: Lotto
on:
  schedule:
    - cron: '0 23 * * 0-4'
# 2025/01
jobs:
  run-actions:
    runs-on: self-hosted
    steps:
      - name: Install dhapi
        run: |
          pip install dhapi --upgrade

      - name: Configure dhapi
        run: |
          cat <<EOF > ~/.dhapi/credentials
          [default]
          username = "${{ secrets.DH_LOTTO_ID }}"
          password = "${{ secrets.DH_LOTTO_PASSWORD }}"
          EOF

      - name: Buy
        run: |
          dhapi buy-lotto645 -y ''
